name: omero2
channels:
  - pytorch
  - ome
  -defaults
dependencies:
  - omero-py
  - jupyter
  - ipykernel
  - scikit-image
  - matplotlib
  - seaborn
  - pathlib
  - numpy
  - scipy
  - pip:
    - czifile
    - omero-rois
